version: "3.8" 
services: 
  nodered: 
      container_name: Nodered #Nombre al contenedor de node-red
      image: nodered/node-red:latest 
      restart: always 
      ports: 
      - 1880:1880 #Puerto de node-red
      depends_on: 
      - influxdb 
  #Influxdb
  influxdb: 
      container_name: InfluxDB #Definir el nombre del contenedor de influxDB
      image: influxdb 
      restart: always 
      environment: 
        - INFLUXDB_DB=grafana #Creación de base de datos
        - INFLUXDB_USER=grafana #Creación de un usuario para grafana
        - INFLUXDB_USER_PASSWORD=password # Creación de una contraseña
        - INFLUXDB_ADMIN_ENABLE=true #Habilita una cuenta de administrador
        - INFLUXDB_ADMIN_USER=admin #Se crea un usuario
        - INFLUXDB_ADMIN_PASSWORD=admin #Se crea una contraseña
#Grafana
  grafana: # Creación del segundo servicio grafana
      container_name: Grafana #Nombre del contenedor de grafana
      image: grafana/grafana 
      restart: always 
      ports: 
      - 3000:3000 #Puerto de grafana
      depends_on: 
      - influxdb 
